import cv2
import numpy as np


class MaskArea():
    """
    The class contains related features of motion masks which is generated by MOG2 in OpenCV
    """

    def __init__(self, contours):
        """Init function for MaskArea"""
        self.contours = contours
        contour_area_list = list(
            map(cv2.contourArea, self.contours)
        ) if len(self.contours) > 0 else list()
        self.count = len(contour_area_list)
        self.total = sum(contour_area_list) if self.count > 0 else 0
        self.avg = self.total / \
            self.count if self.count > 0 else 0
        self.std = np.std(np.array(contour_area_list))
